### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by dbohdan** [arthurschreiber/handlebars.tcl#1]
Please add a license.

**Comment by arthurschreiber** [comment]
I just added one. Are you intending on using this code for something? 😬

**Comment by dbohdan** [comment]
>I just added one.

Great!

>Are you intending on using this code for something? :grimacing:

Maybe! I am looking for a templating library for the next version of https://github.com/tclssg/tclssg. I'll probably fork and modify whichever one I pick, though.

**Comment by dbohdan** [comment]
(Plus, I'm cleaning up https://wiki.tcl-lang.org/2084. Part of that is making sure all the projects listed have a clear license. :-) )
